accounts/urls.py
from django.urls import path

from .views import signup_view, dashboard_view, home_view

app_name = 'accounts'

urlpatterns = [
	path('', home_view, name='home'),
	path('dashboard/', dashboard_view, name='dashboard'),
	path('register/', signup_view, name='register'),
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include('accounts.urls', namespace='accounts')),
]

urlpatterns += [
    path('api-auth-token/', obtain_jwt_token),
    path('api-token-refresh/', refresh_jwt_token),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

class User(AbstractUser):
	email = models.EmailField(_('email address'), max_length=150, unique=True)

blogs/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	email = forms.EmailField(
		label='',
		max_length=254,
		widget=forms.EmailInput(
			attrs={
				"placeholder": "Email",
				"class": "form-control"
			}
		)
	)

	username = forms.CharField(
		label='',
		max_length=30,
		min_length=5,
		required=True,
		widget=forms.TextInput(
			attrs={
				"placeholder": "Username",
				"class": "form-control"
			}
		)
	)

	password1 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Password",
				"class": "form-control"
			}
		)
	)

	password2 = forms.CharField(
		label='',
		max_length=30,
		min_length=8,
		required=True,
		widget=forms.PasswordInput(
			attrs={
				"placeholder": "Confirm Password",
				"class": "form-control"
			}
		)
	)
	
	class Meta:
		model = User
		fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import SignUpForm

def signup_view(request):
	if request.method == "POST":
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=password)
			login(request, user)
			return redirect('accounts:dashboard')
		else:
			messages.error(request, 'Correct the errors below')
	else:
		form = SignUpForm()

	return render(request, 'app/signup.html', {'form': form})


@login_required
def dashboard_view(request):
	return render(request, 'app/dashboard.html')


def home_view(request):
	return render(request, 'app/home.html')

blogs/views.py
from django.shortcuts import render

# Create your views here.

templates/app/dashboard.html
{% extends "base.html" %}

{% block title %}
	Dashboard
{% endblock %}

{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

	<h1 class="mt-5 text-center">Welcome {{ request.user }}</h1>
	<p class="text-left mt-5">Bio: {{ user.profile.bio }}</p>
	<p class="text-left">Joined: {{ user.profile.timestamp }}</p>

{% endblock content %}

templates/app/home.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}

	{{ block.super }}

{% endblock content %}

templates/app/signup.html
{% extends "base.html" %}

{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="container mt-4">
<div class="row">
	<div class="col-md-4">
		
		<div class="list-group mt-5">
		    <a href="{% url 'accounts:home' %}" class="list-group-item list-group-item-action waves-effect">Home</a>
		    <a href="{% url 'accounts:register' %}" class="list-group-item bg-secondary text-white waves-effect">
		    	Register
		    </a>
		    <a href="{% url 'login' %}" class="list-group-item list-group-item-action waves-effect">Login</a>
		    <a href="{% url 'accounts:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Dashboard</a>
		</div>

	</div>

		<div class="col-md-2"></div>

	<div class="col-md-4">
		<!-- Default form register -->
		<form class="border mt-5 border-secondary text-center p-3" method="post">
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center">Sign up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

		    <!-- Social register -->
		    <p>or sign up with:</p>

		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-facebook"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-twitter"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-linkedin"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-github"></i>
		    </a>

		    <hr>

		    <!-- Terms of service -->
		    <p>By clicking
		        <em>Sign up</em> you agree to our
		        <a href="" target="_blank">terms of service</a>
		    </p>
		</form>
		<!-- Default form register -->
	</div>

	<div class="col-md-2"></div>

</div>
</div>

{% block script %}
<script type="text/javascript">
	function get_ip(json) {
		$("#id_location").val(json.ip);
	}
</script>

<script src="https://api.ipify.org?format=jsonp&callback=get_ip"></script>
{% endblock %}

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Django App | {% block title %}{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>

  <body>

    {% if not form %}
      {% include "navbar.html" %}
    {% endif %}

      <!-- Start your project here-->
      <div style="height: 100vh" class="container">

      	{% block content %}

          <div class="flex-center flex-column">
              <h1 class="animated fadeIn mb-4">Material Design for Bootstrap</h1>

              <h5 class="animated fadeIn mb-3">Thank you for using our product. We're glad you're with us.</h5>

              <p class="animated fadeIn text-muted">MDB Team</p>
          </div>

        {% endblock %}
      </div>
      <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block script %}
    {% endblock %}
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>